In [5]:
import numpy as np

In [119]:
#1
arr = np.array([[2,3,5],[4,6,8],[11,13,17],[7,10,13]]) 
def containsPrimes(arr):
    def is_prime(n):
        if n <= 1:
            return False
        if n <= 3:
            return True
        if n % 2 == 0 or n % 3 ==0:
            return False
        i = 5
        while i * i <= n:
            if n % i == 0 or n % (i + 2) == 0:
                return False
            i += 6 
        return True
    prime_rows = np.array([any(is_prime(n) for n in row) for row in arr])
    return prime_rows

print(containsPrimes(arr))

[ True False  True  True]


In [21]:
#2.1
def checkerboard(size):
    return np.zeros((size,size))

In [23]:
print(checkerboard(8))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [91]:
#2.2
def alternating_rows(num_rows, num_cols):
    matrix = np.zeros((num_rows,num_cols))
    for i in range(num_rows):
        if (i + 1) % 2 != 0: 
            for j in range(num_cols):
                if (j + 1) % 2 != 0:
                    matrix[i,j]=1
    return matrix

print(alternating_rows(8,8))

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [57]:
#2.3
def alternating_evens(num_rows, num_cols):
    matrix = np.zeros((num_rows,num_cols))
    for i in range(num_rows):
        if i % 2 != 0: 
            for j in range(num_cols):
                if j % 2 != 0:
                    matrix[i,j]=1
    matrix = np.zeros((num_rows,num_cols))
    for f in range(num_rows):
            if (f + 1) % 2 != 0: 
                for l in range(num_cols):
                    if (l + 1) % 2 != 0:
                        matrix[f,l]=1
    return matrix

print (alternating_evens(8,8))
#ok i'm ngl idk what i cooked up here but smth is clearly wrong so ignore this it's fixed below lol

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [109]:
#2.3
x = np.zeros((8, 8))
x[1:8:2, 1:8:2] = 1
x[0:8:2, 0:8:2] = 1
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [101]:
#2.4
x = np.zeros((8,8))
x[0:8:2, 1:8:2] = 1
x[1:8:2, 0:8:2] = 1
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [85]:
#3
universe = np.array(['galaxy', 'clusters'])
def expansion(text, num_spaces):
    arr = []
    for character in text:
        result = ''
        for letter in character:
            result += letter + ' ' * num_spaces
        arr.append(result)
    return arr

print(expansion(universe,2))
#done

['g  a  l  a  x  y  ', 'c  l  u  s  t  e  r  s  ']


In [123]:
#4
def secondDimmest(arr):
    sorted_arr = np.sort(arr, axis=0)
    return sorted_arr[1]

np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print("Star luminosities:\n", stars)

print("Second dimmest in each cluster:", secondDimmest(stars))

#ok nah I'm gettin confused betwen the hint notation and the google examples I'm seeing but hopefully this is right ehe

Star luminosities:
 [[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
Second dimmest in each cluster: [ 611 1108 1732 1346  724]
